language: node_js
node_js:
  - "8.4"
sudo: false
cache:
  directories:
    - $HOME/.npm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - npm t
  - npm i react-native-cli -g
  - react-native bundle --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --platform ios
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      sudo: required
      node_js: false
      before_install:
        - nvm install 8
        - node --version
      install:
        - travis_retry npm i -d
      android:
        components:
          - build-tools-25.0.0
          - android-25
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleDebug && ./gradlew assembleRelease
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      node_js: false
      before_install:
        - nvm install 8
        - node --version
      install:
        - travis_retry gem install xcpretty
        - travis_retry npm i -d
      xcode_project: ios/edge.xcworkspace
      xcode_scheme: ios/edge
      script:
        - cd ios
        - xcodebuild -scheme edge -project edge.xcodeproj archive ONLY_ACTIVE_ARCH=NO
