language: node_js
node_js:
  - 14
before_install:
  - cp env.example.json env.json
install:
  - yarn install --frozen-lockfile --ignore-optional --network-concurrency 1
script:
  - yarn lint
  - yarn flow
  - npm run test
