language: node_js
cache: yarn
sudo: false
node_js:
  - "11.4.0"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH="$HOME/.yarn/bin:$PATH"
script:
  - npm run security
  - npm run test
